name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    defaults:
      run:
        working-directory: manasa-package
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm ci
    # - run: npm run lint
    # - run: npm run build
    # TODO - tests
    # - run: npm test

  package:
    defaults:
      run:
        working-directory: manasa-package
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - run: npm ci
      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "manasa-package/*.tgz"

  publish:
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/download-artifact@v2
      with:
          name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://npm.pkg.github.com/
        # scope: "@aaronpowell"
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}