name: Publish NPM Package
on:
  release:
    types: [created]
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm ci
    - name: Release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: nvm install 'lts/*' && npx semantic-release


